# Produce a build suitable for release, i.e. use PGO/LTO. You can turn it off
# when building locally to reduce build time.
%global release_build     1

# Run Mozilla test suite as a part of compile rpm section. Turn off when
# building locally and don't want to spend 24 hours waiting for results.
%global run_firefox_tests 0
%ifarch x86_64 %{ix86}
%global run_firefox_tests 0
%endif

# Don't create debuginfo rpm packages. It reduces build time as
# exctracting debuginfo takes long time.
%global create_debuginfo  1

# Produce debug (non-optimized) package build. Suitable for debugging only
# as the build is *very* slow.
%global debug_build       0

%global system_nss        1
%global build_with_asan   0
%global test_on_wayland   1

%if "%{toolchain}" == "clang"
%global build_with_clang 1
%else
%global build_with_clang 0
%endif

# There are still build problems on s390x, see
# https://koji.fedoraproject.org/koji/taskinfo?taskID=55048351
# https://bugzilla.redhat.com/show_bug.cgi?id=1897522
ExcludeArch: s390x

# Disabled due to
# https://bugzilla.redhat.com/show_bug.cgi?id=1966949
%if 0%{?fedora} > 33
ExcludeArch: armv7hl
%endif

%ifarch armv7hl
%global create_debuginfo  0
%endif

# Temporary disabled due to
# https://bugzilla.redhat.com/show_bug.cgi?id=1951606
%global enable_mozilla_crashreporter 0
%ifarch x86_64 %{ix86}
%global enable_mozilla_crashreporter 1
%endif
%if %{build_with_asan}
%global enable_mozilla_crashreporter 0
%endif
%if 0%{?flatpak}
%global enable_mozilla_crashreporter 0
%endif
%if !%{create_debuginfo}
%define _unpackaged_files_terminate_build 0
%global debug_package %{nil}
%global enable_mozilla_crashreporter 0
%endif

%global system_ffi        1
%ifarch armv7hl
%global system_libvpx     1
%else
%global system_libvpx     0
%endif
%global hardened_build    1
%global system_jpeg       1
%global disable_elfhack   1
%global use_bundled_cbindgen  1
%if %{debug_build}
%global release_build     0
%endif
# Build PGO+LTO on x86_64 and aarch64 only due to build issues
# on other arches.
%global build_with_pgo    0
%ifarch x86_64
%if %{release_build}
%global build_with_pgo    1
%endif
%endif
%if 0%{?flatpak}
%global build_with_pgo    0
%endif
# Big endian platforms
%ifarch ppc64 s390x
%global big_endian        1
%endif

%if 0%{?build_with_pgo}
%global use_xvfb          1
%global build_tests       1
%endif

%if 0%{?run_firefox_tests}
%global use_xvfb          1
%global build_tests       1
%endif

%global launch_wayland_compositor 0
%if %{build_with_pgo} && %{test_on_wayland}
%global launch_wayland_compositor 1
%endif
%if %{run_firefox_tests} && %{test_on_wayland}
%global launch_wayland_compositor 1
%endif

%global default_bookmarks_file  %{_datadir}/bookmarks/default-bookmarks.html
%global firefox_app_id  \{ec8030f7-c20a-464f-9b0e-13a3a9e97384\}
# Minimal required versions
%global cairo_version 1.13.1
%global freetype_version 2.1.9
%global libnotify_version 0.7.0
%if %{?system_libvpx}
%global libvpx_version 1.8.2
%endif

%if %{?system_nss}
%global nspr_version 4.26
%global nspr_build_version %{nspr_version}
%global nss_version 3.69
%global nss_build_version %{nss_version}
%endif

%global mozappdir     %{_libdir}/librewolf
%global mozappdirdev  %{_libdir}/librewolf-devel-%{version}
%global langpackdir   %{mozappdir}/langpacks
%global tarballdir    firefox-%{version}

%global official_branding       1

%bcond_with langpacks

%if !%{release_build}
%global pre_tag .npgo
%endif
%if %{build_with_clang}
%global pre_tag .clang
%endif
%if %{build_with_asan}
%global pre_tag .asan
%global build_with_pgo    0
%endif
%if !%{system_nss}
%global nss_tag .nss
%endif
%if %{debug_build}
%global pre_tag .debug
%endif

# Exclude private libraries from autogenerated provides and requires
%global __provides_exclude_from ^%{mozappdir}
%global __requires_exclude ^(%%(find %{buildroot}%{mozappdir} -name '*.so' | xargs -n1 basename | sort -u | paste -s -d '|' -))


Name:           firedragon
%global enable_mozilla_crashreporter 0
Version:        109.0
Release:        %{?dist}
Summary:        Librewolf fork build using custom branding, settings & KDE patches by OpenSUSE
License:        MPL
URL:            https://gitlab.com/dr460nf1r3/settings/

Source0:        https://archive.mozilla.org/pub/firefox/releases/109.0/source/firefox-109.0.source.tar.xz
Source1:        https://archive.mozilla.org/pub/firefox/releases/109.0/source/firefox-109.0.source.tar.xz.asc
Source2:        firedragon.desktop
Source3:        git+https://gitlab.com/dr460nf1r3/common.git
Source4:        git+https://gitlab.com/dr460nf1r3/settings.git
Source5:        librewolf-source::git+https://gitlab.com/librewolf-community/browser/source.git
Source6:        librewolf-settings::git+https://gitlab.com/librewolf-community/settings.git
Source7:        cachyos-source::git+https://github.com/CachyOS/CachyOS-Browser-Common.git



%changelog
* Пн янв 30 2023 Andrey Savich  <46422808+pieckenst@users.noreply.github.com> - 109.0
- Initial version
